<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="514" started-at="2018-11-22T18:07:22Z" finished-at="2018-11-22T18:07:22Z">
    <groups>
      <group name="requiresPgSQL">
        <method signature="PgSQLConnectionManagerTest.testGetConnection()[pri:0, instance:com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest@31dc339b]" name="testGetConnection" class="com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest"/>
        <method signature="PgSQLConnectionManagerTest.testShutdown()[pri:0, instance:com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest@31dc339b]" name="testShutdown" class="com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest"/>
        <method signature="PgSQLConnectionManagerTest.testTestConnection()[pri:0, instance:com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest@31dc339b]" name="testTestConnection" class="com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest"/>
      </group> <!-- requiresPgSQL -->
    </groups>
    <test name="Default test" duration-ms="514" started-at="2018-11-22T18:07:22Z" finished-at="2018-11-22T18:07:22Z">
      <class name="com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest">
        <test-method status="PASS" signature="beforeTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest@31dc339b]" test-instance-name="" name="beforeTest" is-config="true" duration-ms="266" started-at="2018-11-22T18:07:22Z" finished-at="2018-11-22T18:07:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[testdb]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[127.0.0.1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5432]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[postgres]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[test_data]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="testGetConnection()[pri:0, instance:com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest@31dc339b]" test-instance-name="" name="testGetConnection" duration-ms="170" started-at="2018-11-22T18:07:22Z" finished-at="2018-11-22T18:07:22Z">
          <exception class="com.google.refine.extension.database.DatabaseServiceException">
            <message>
              <![CDATA[FATAL: authentification par mot de passe échouée pour l'utilisateur  « postgres »]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.google.refine.extension.database.DatabaseServiceException: FATAL: authentification par mot de passe échouée pour l'utilisateur  « postgres »
	at com.google.refine.extension.database.pgsql.PgSQLConnectionManager.getConnection(PgSQLConnectionManager.java:159)
	at com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest.testGetConnection(PgSQLConnectionManagerTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.google.refine.extension.database.DatabaseServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetConnection -->
        <test-method status="FAIL" signature="testShutdown()[pri:0, instance:com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest@31dc339b]" test-instance-name="" name="testShutdown" duration-ms="13" started-at="2018-11-22T18:07:22Z" finished-at="2018-11-22T18:07:22Z">
          <exception class="com.google.refine.extension.database.DatabaseServiceException">
            <message>
              <![CDATA[FATAL: authentification par mot de passe échouée pour l'utilisateur  « postgres »]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.google.refine.extension.database.DatabaseServiceException: FATAL: authentification par mot de passe échouée pour l'utilisateur  « postgres »
	at com.google.refine.extension.database.pgsql.PgSQLConnectionManager.getConnection(PgSQLConnectionManager.java:159)
	at com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest.testShutdown(PgSQLConnectionManagerTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.google.refine.extension.database.DatabaseServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testShutdown -->
        <test-method status="FAIL" signature="testTestConnection()[pri:0, instance:com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest@31dc339b]" test-instance-name="" name="testTestConnection" duration-ms="23" started-at="2018-11-22T18:07:22Z" finished-at="2018-11-22T18:07:22Z">
          <exception class="com.google.refine.extension.database.DatabaseServiceException">
            <message>
              <![CDATA[FATAL: authentification par mot de passe échouée pour l'utilisateur  « postgres »]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.google.refine.extension.database.DatabaseServiceException: FATAL: authentification par mot de passe échouée pour l'utilisateur  « postgres »
	at com.google.refine.extension.database.pgsql.PgSQLConnectionManager.getConnection(PgSQLConnectionManager.java:159)
	at com.google.refine.extension.database.pgsql.PgSQLConnectionManager.testConnection(PgSQLConnectionManager.java:107)
	at com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest.testTestConnection(PgSQLConnectionManagerTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.google.refine.extension.database.DatabaseServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTestConnection -->
      </class> <!-- com.google.refine.extension.database.pgsql.PgSQLConnectionManagerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
